### ISSUE TITLE
Jekyll website ?

### ISSUE THREAD

**Issue by jooola** [Libresonic/Libresonic.github.io#3]
I suggest using Jekyll to build the website, everyone is OK with that ?

**Comment by EugeneKay** [comment]
Yup, that's the intent of this repository! 

At present [www.]libresonic.org redirects to https://github.com/Libresonic/libresonic. Using Jekyll+Github Pages I would create an alias at www.libresonic.org to the Github-hosted site. The bare domain(libresonic.org) would have a 301 forward.

At present none of this has been done for a variety of reasons, but it boils down to "nobody has built a site yet". So if you'd like to take point, go for it! Let me know what access you need.

**Comment by jooola** [comment]
Ok, i'll build the website in a fork for now !

**Comment by jooola** [comment]
@EugeneKay I need some help for the content. I don't speak a really good english and i don't think copy pasting is really good right now. Could we mix up something ?

**Comment by jooola** [comment]
I don't konw what you think @EugeneKay but I think we kind a have a website now

**Comment by EugeneKay** [comment]
@jooola Thanks for the hard work! I am going to attach this to the 6.3 milestone, but I anticipate that it will go live sooner than that.

**Comment by jooola** [comment]
@EugeneKay So we synced the documentation repo with the website documentation folder, The website has seen some great improvements !
Submoduling the documentation repo here is planned for today.

So i suggest we go live with the website since the documentation is easier to understand !

Reading your first comment I still have a question: what will the FQDN be ? Did this changed ?
www.libresonic.org/
Or are we keeping the
libresonic.github.io ?

Could we force the use of HTTPS ?

Hope we can go live in the next 3 days ! ( when you have the time :p )
